### ISSUE TITLE
Please add LICENSE, license headers to code, contribution guidelines and code of conduct

### ISSUE THREAD

**Issue by filmaj** [Adobe-Marketing-Cloud/aep-target-sdk#1]
Hey, Fil from Adobe's Open Source Office here.

Before open sourcing it is important to ensure you have legal bits in place like a license, code has source code headers that are compatible with your chosen license, contribution guidelines that make clear to external contributors the need to sign a CLA, and our Adobe Legal-approved code of conduct.

You can copy these files from github.com/adobe/starter-repo.

If the above is confusing or you have more questions, we highly recommend you fill out the form at opensource.corp.adobe.com, where members from the Open Source Office can help set you up with all of that and make sure to do the requisite checks.

**Comment by bipul-agarwal** [comment]
Added License, Contribution guidelines and Code of Conduct.
License headers to code will be added as they are added in repo.
